#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'cpplint==1.4.4','console_scripts','cpplint'
__requires__ = 'cpplint==1.4.4'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('cpplint==1.4.4', 'console_scripts', 'cpplint')()
    )
